---
title: "Advent Of Code 2023"
author: "Alanah Grant-St James"
date: "2023-12-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Library
```{r}
library(magrittr)
library(readr)
library(stringr)
library(dplyr)
library(spatstat.utils)
```


#Day 1.1
```{r}
data <- read.delim("data/day1.txt", header = FALSE)
data$remove_letters <- gsub("[^0-9]", "", data$V1)
data$first_num <- substr(data$remove_letters, 1, 1)
data$last_num <- NA
for (row in data$remove_letters) {
  len <- nchar(row)
  data$last_num[data$remove_letters==row] <- substr(data$remove_letters[data$remove_letters==row], len, len+1)
}

data$final_num <- as.numeric(paste0(data$first_num, data$last_num))
sum(data$final_num)
```
#Day 1.2
```{r}
data <- read.delim("data/day1.txt", header = FALSE)
data$adjusted <- data$V1
data$adjusted <- gsub("oneight", "18", data$adjusted)
data$adjusted <- gsub("threeight", "38", data$adjusted)
data$adjusted <- gsub("fiveight", "58", data$adjusted)
data$adjusted <- gsub("nineight", "98", data$adjusted)
data$adjusted <- gsub("eightwo", "82", data$adjusted)
data$adjusted <- gsub("eighthree", "83", data$adjusted)
data$adjusted <- gsub("twone", "21", data$adjusted)
data$adjusted <- gsub("sevenine", "79", data$adjusted)

data$adjusted <- gsub("one", "1", data$adjusted)
data$adjusted <- gsub("two", "2", data$adjusted)
data$adjusted <- gsub("three", "3", data$adjusted)
data$adjusted <- gsub("four", "4", data$adjusted)
data$adjusted <- gsub("five", "5", data$adjusted)
data$adjusted <- gsub("six", "6", data$adjusted)
data$adjusted <- gsub("seven", "7", data$adjusted)
data$adjusted <- gsub("eight", "8", data$adjusted)
data$adjusted <- gsub("nine", "9", data$adjusted)
data$remove_letters <- gsub("[^0-9]", "", data$adjusted)
data$first_num <- substr(data$remove_letters, 1, 1)
data$last_num <- NA
for (row in data$remove_letters) {
  len <- nchar(row)
  data$last_num[data$remove_letters==row] <- substr(data$remove_letters[data$remove_letters==row], len, len+1)
}

data$final_num <- as.numeric(paste0(data$first_num, data$last_num))
sum(data$final_num)
```
#Day 2.1
```{r}
data <- read.delim("data/day2.txt", header = FALSE)
# remove "Game "
data$V1 <- gsub("Game ", "", data$V1)
data$game_index <- NA
data$red <- 0
data$blue <- 0
data$green <- 0
for (n in 1:length(data$V1)) {
  data$game_index[n] <- str_split(data$V1[n], ": ")[[1]][1]
  games <- str_split(data$V1[n], ": ")[[1]][2]
  rounds <- str_split(games, "; ")[[1]]
  for (round in c(1:length(rounds))) {
    # print(round)
    round_data <- rounds[round]
    test_data <- str_split(round_data, ", ")
    for (info_num in c(1:length(test_data[[1]]))) {
      if (grepl("red", test_data[[1]][info_num])) {
        data$red[n] <- max(
          c(data$red[n], 
            as.numeric(gsub("[^0-9]", "", test_data[[1]][info_num]))))
      }
      if (grepl("blue", test_data[[1]][info_num])) {
        data$blue[n] <- max(
          c(data$blue[n], 
            as.numeric(gsub("[^0-9]", "", test_data[[1]][info_num]))))
      }
      if (grepl("green", test_data[[1]][info_num])) {
        data$green[n] <- max(
          c(data$green[n], 
            as.numeric(gsub("[^0-9]", "", test_data[[1]][info_num]))))
      }
    }
  }
}

data_reduced <- data[data$red <= 12 & data$blue <= 14 & data$green <= 13, ]

sum(as.numeric(data_reduced$game_index))

```
#Day 2.2
```{r}
data$power <- data$red * data$blue * data$green
sum(data$power)
```
#Day 3.1
```{r}
data <- read.delim("data/day3.txt", header = FALSE)
data$numbers_and_symbols <- strsplit(data$V1, split = "(?=[[:punct:]])", perl = TRUE)

symbols <- matrix(FALSE, nrow = 140, ncol = 140)
data1 <- t(matrix(unlist(strsplit(data$V1, split = "")), nrow = 140, ncol = 140))
numbers <- character()
for (row in c(1:nrow(data1))) {
  for (col in c(1:ncol(data1))) {
    if (grepl("(?![.])[[:punct:]]", data1[row, col], perl = TRUE)) {
      symbols[row, col] = TRUE
    }
  }
}

for (row in c(1:length(data$numbers_and_symbols))) {
  current_row <- data$numbers_and_symbols[row][[1]]
  for (split in c(1:length(current_row))) {
    if (grepl("[[:digit:]]", current_row[split])) {
      first_index <- sum(nchar(current_row[1:split-1])) +1
      last_index <- sum(nchar(current_row[1:split-1])) + nchar(current_row[split])
      
      # check if there is any punctuation (other than .) around number
      check_indexes_r1 <- c((first_index-1):(last_index+1))
      check_indexes_r2 <- c((first_index-1), (last_index+1))
      check_indexes_r3 <- c((first_index-1):(last_index+1))
      
     
      if (first_index == 1) {
        check_indexes_r1 <- check_indexes_r1[-1]
        check_indexes_r2 <- check_indexes_r2[-1]
        check_indexes_r3 <- check_indexes_r3[-1]
      }
      if (last_index == nchar(data$V1[row])) {
        check_indexes_r1 <- check_indexes_r1[-length(check_indexes_r1)]
        check_indexes_r2 <- check_indexes_r2[-length(check_indexes_r2)]
        check_indexes_r3 <- check_indexes_r3[-length(check_indexes_r3)]
      }
      
      if (row == 1) {
        characters_to_check <- c(
          data1[row, check_indexes_r2], 
          data1[row + 1, check_indexes_r3]
          )
      } else if (row == length(data$V1)) {
        characters_to_check <- c(
          data1[row-1, check_indexes_r1],
          data1[row, check_indexes_r2]
          )
      } else {
        characters_to_check <- c(
          data1[row-1, check_indexes_r1],
          data1[row, check_indexes_r2], 
          data1[row + 1, check_indexes_r3]
          )
      }
      
      if (any(grepl("(?![.])[[:punct:]]", characters_to_check, perl = TRUE))) {
        numbers <- c(numbers, current_row[split])
      }
    }
  }
}

sum(as.numeric(numbers))
```
# Day 3.2
```{r}
data <- read.delim("data/day3.txt", header = FALSE)
data$numbers_and_symbols <- strsplit(data$V1, split = "(?=[[:punct:]])", perl = TRUE)

asterisks <- matrix(FALSE, nrow = 140, ncol = 140)
data1 <- t(matrix(unlist(strsplit(data$V1, split = "")), nrow = 140, ncol = 140))
numbers <- character()
for (row in c(1:nrow(data1))) {
  for (col in c(1:ncol(data1))) {
    if (grepl("\\*", data1[row, col], perl = TRUE)) {
      asterisks[row, col] = TRUE
    }
  }
}

number_id_matrix <- matrix(0, nrow = 140, ncol = 140)
for (row in c(1:length(data$numbers_and_symbols))) {
  current_row <- data$numbers_and_symbols[row][[1]]
  for (split in c(1:length(current_row))) {
    if (grepl("[[:digit:]]", current_row[split])) {
      first_index <- sum(nchar(current_row[1:split-1])) +1
      last_index <- sum(nchar(current_row[1:split-1])) + nchar(current_row[split])
      number_id_matrix[row, c(first_index:last_index)] <- as.numeric(current_row[split])
    }
  }
}

gear_ratios <- numeric()
for (row in c(1:nrow(asterisks))) {
  for (col in c(1:ncol(asterisks))) {
    if (asterisks[row, col] == TRUE) {
    # check if there is any punctuation (other than .) around number
      check_indexes_r1 <- c(col-1, col, col+1)
      check_indexes_r2 <- c(col-1, col+1)
      check_indexes_r3 <- c(col-1, col, col+1)
      
     
      if (col == 1) {
        check_indexes_r1 <- check_indexes_r1[-1]
        check_indexes_r2 <- check_indexes_r2[-1]
        check_indexes_r3 <- check_indexes_r3[-1]
      }
      if (col == 140) {
        check_indexes_r1 <- check_indexes_r1[-length(check_indexes_r1)]
        check_indexes_r2 <- check_indexes_r2[-length(check_indexes_r2)]
        check_indexes_r3 <- check_indexes_r3[-length(check_indexes_r3)]
      }
      
      if (row == 1) {
        positions_to_check <- c(
          number_id_matrix[row, check_indexes_r2], 
          number_id_matrix[row + 1, check_indexes_r3]
          )
      } else if (row == length(data$V1)) {
        positions_to_check <- c(
          number_id_matrix[row-1, check_indexes_r1],
          number_id_matrix[row, check_indexes_r2]
          )
      } else {
        positions_to_check <- c(
          number_id_matrix[row-1, check_indexes_r1],
          number_id_matrix[row, check_indexes_r2], 
          number_id_matrix[row + 1, check_indexes_r3]
          )
      }
      positions_to_check <- unique(positions_to_check[positions_to_check!=0])
      if (length(positions_to_check) == 2) {
        gear_ratios <- c(gear_ratios, positions_to_check[1] * positions_to_check[2])
      }
    }
  }
}

sum(gear_ratios)
```
#Day 5.1 - HELP
```{r}
data <- read.delim("data/day5.txt", header = FALSE)

# maps
seed_to_soil_data <- as.numeric(unlist(strsplit(data$V1[(which(data$V1=="seed-to-soil map:")+1):(which(data$V1 == "soil-to-fertilizer map:")-1)], split = " ")))
seed_to_soil_map <- data.frame(t(matrix(seed_to_soil_data, nrow = 3)))
colnames(seed_to_soil_map) <- c("destination_start", "source_start", "length")

soil_to_fertilizer_data <- as.numeric(unlist(strsplit(data$V1[(which(data$V1=="soil-to-fertilizer map:")+1):(which(data$V1 == "fertilizer-to-water map:")-1)], split = " ")))
soil_to_fertilizer_map <- data.frame(t(matrix(soil_to_fertilizer_data, nrow = 3)))
colnames(soil_to_fertilizer_map) <- c("destination_start", "source_start", "length")

fertilizer_to_water_data <- as.numeric(unlist(strsplit(data$V1[(which(data$V1=="fertilizer-to-water map:")+1):(which(data$V1 == "water-to-light map:")-1)], split = " ")))
fertilizer_to_water_map <- data.frame(t(matrix(fertilizer_to_water_data, nrow = 3)))
colnames(fertilizer_to_water_map) <- c("destination_start", "source_start", "length")

water_to_light_data <- as.numeric(unlist(strsplit(data$V1[(which(data$V1=="water-to-light map:")+1):(which(data$V1 == "light-to-temperature map:")-1)], split = " ")))
water_to_light_map <- data.frame(t(matrix(water_to_light_data, nrow = 3)))
colnames(water_to_light_map) <- c("destination_start", "source_start", "length")

light_to_temperature_data <- as.numeric(unlist(strsplit(data$V1[(which(data$V1=="light-to-temperature map:")+1):(which(data$V1 == "temperature-to-humidity map:")-1)], split = " ")))
light_to_temperature_map <- data.frame(t(matrix(light_to_temperature_data, nrow = 3)))
colnames(light_to_temperature_map) <- c("destination_start", "source_start", "length")

temperature_to_humidity_data <- as.numeric(unlist(strsplit(data$V1[(which(data$V1=="temperature-to-humidity map:")+1):(which(data$V1 == "humidity-to-location map:")-1)], split = " ")))
temperature_to_humidity_map <- data.frame(t(matrix(temperature_to_humidity_data, nrow = 3)))
colnames(temperature_to_humidity_map) <- c("destination_start", "source_start", "length")

humidity_to_location_data <- as.numeric(unlist(strsplit(data$V1[(which(data$V1=="humidity-to-location map:")+1):length(data$V1)], split = " ")))
humidity_to_location_map <- data.frame(t(matrix(humidity_to_location_data, nrow = 3)))
colnames(humidity_to_location_map) <- c("destination_start", "source_start", "length")

maps <- list(seed_to_soil_map, soil_to_fertilizer_map, fertilizer_to_water_map, water_to_light_map, light_to_temperature_map, temperature_to_humidity_map, humidity_to_location_map)

seeds <- strsplit(data$V1[1], split = " ")[[1]][-1]
df <- data.frame(seed = as.numeric(seeds), 
                 soil = NA, 
                 fertilizer = NA, 
                 water = NA, 
                 light = NA, 
                 temperature = NA, 
                 humidity = NA, 
                 location = NA)

# for each seed
for (seed_row in c(1:length(df$seed))) {
  # for each column (plant need)
  for (col in c(1:length(colnames(df)[-1]))) {
    #set range_found flag to FALSE
    range_found = FALSE
    # for each row in the map
    for (row in c(1:length(maps[[col]]))) {
      # check if the seed is in range
      if (range_found == FALSE) {
        if (inside.range(
          df[seed_row, col], 
          range(
            maps[[col]]$source_start[row], 
            maps[[col]]$source_start[row] + maps[[col]]$length[row]-1))) { #-1 as the first number counts in the range
          # if it is, flag
          range_found = TRUE
          
          #plant need destination value is the destination start value + difference between source start and source value
          df[seed_row, col+1] <- maps[[col]]$destination_start[row] + (df[seed_row, col] - maps[[col]]$source_start[row])
        }
      }
    }
    # if range isn't found, destination is the same as source
    if (range_found == FALSE) {
      df[seed_row, col+1] <- df[seed_row, col]
    }
  }
}

min(df$location)
```
# Day 6.1
```{r}
data <- read.delim("data/day6.txt", header = FALSE)
time <- as.numeric(strsplit(data[1, 1], split = " ")[[1]][grepl("[[:digit:]]", strsplit(data[1, 1], split = " ")[[1]])])
distance <- as.numeric(strsplit(data[2, 1], split = " ")[[1]][grepl("[[:digit:]]", strsplit(data[2, 1], split = " ")[[1]])])
df <- data.frame(time = time, distance = distance, race_results = NA)


for (race in 1:nrow(df)) {
  race_strat <- data.frame(hold_ms = NA, 
                         sail_ms = NA, 
                         total_distance = NA)
  for (ms in 1:df[race, "time"]) {
    race_strat[ms, ] <- data.frame(hold_ms = ms, 
                                   sail_ms = df[race, "time"] - ms, 
                                   distance = ms * (df[race, "time"] - ms))
    
  }
  df[race, "race_results"] <- length(race_strat$total_distance[race_strat$total_distance > df$distance[race]])
}

prod(df$race_results)
```
# Day 6.2
```{r}
data <- read.delim("data/day6.txt", header = FALSE)
data$V2<- as.numeric(gsub("[^0-9]", "", data$V1))


for (ms in 1:data[1, 2]) {
  if (ms * (data[1, 2] - ms) > data[2,2]) {
    print(ms)
    break
  }
}

print(data[1,2] - 2*(ms-1)) # because inclusive
# it's 42948149? not sure why
```
# Day 7.1
```{r}
data <- read.delim("data/day7.txt", header = FALSE)

df<- as.data.frame(t(data.frame(strsplit(data$V1, split = " "))))
colnames(df) <- c("hand", "bid")
rownames(df) <- c(1:nrow(df))
df$bid <- as.numeric(df$bid)
df$type <- NA
df$one <- NA
df$two <- NA
df$three <- NA
df$four <- NA
df$five <- NA

for (row in 1:nrow(df)) {
  split_string <- strsplit(df$hand[row], split = "")[[1]]
  df$type[row] <- ifelse(length(unique(split_string))==1, 
                         "five-of-a-kind", 
                         ifelse(
                           (length(unique(split_string))==2) &
                           (sum(split_string %in% unique(split_string)[1]) %in% c(1,4)) &
                           (sum(split_string %in% unique(split_string)[2]) %in% c(1,4)), 
                            "four-of-a-kind",
                              ifelse(
                             (length(unique(split_string))==2) &
                             (sum(split_string %in% unique(split_string)[1]) %in% c(2,3)) &
                               (sum(split_string %in% unique(split_string)[2]) %in% c(2,3)),
                             "full-house", 
                             ifelse(
                               (length(unique(split_string))==3) &
                               (sum(split_string %in% unique(split_string)[1]) %in% c(1,3)) &
                               (sum(split_string %in% unique(split_string)[2]) %in% c(1,3))&
                               (sum(split_string %in% unique(split_string)[3]) %in% c(1,3)),
                               "three-of-a-kind", 
                               ifelse(
                                  (length(unique(split_string))==3) &
                               (sum(split_string %in% unique(split_string)[1]) %in% c(1,2)) &
                               (sum(split_string %in% unique(split_string)[2]) %in% c(1,2)) &
                               (sum(split_string %in% unique(split_string)[3]) %in% c(1,2)), 
                               "two-pair", 
                               ifelse(
                                 (length(unique(split_string))==4), 
                                 "one-pair", 
                                 "high-card"))))))
  
  df$one[row] <- strsplit(df$hand[row], split = "")[[1]][1]
  df$two[row] <- strsplit(df$hand[row], split = "")[[1]][2]
  df$three[row] <- strsplit(df$hand[row], split = "")[[1]][3]
  df$four[row] <- strsplit(df$hand[row], split = "")[[1]][4]
  df$five[row] <- strsplit(df$hand[row], split = "")[[1]][5]
}
df$type <- factor(df$type, ordered = TRUE, levels = c("five-of-a-kind", "four-of-a-kind", "full-house", "three-of-a-kind", "two-pair", "one-pair", "high-card"))
df$one <- ordered(df$one, levels = c("A", "K", "Q", "J", "T", "9", "8", "7", "6", "5", "4", "3", "2", "1"))
df$two <- ordered(df$two, levels = c("A", "K", "Q", "J", "T", "9", "8", "7", "6", "5", "4", "3", "2", "1"))
df$three <- ordered(df$three, levels = c("A", "K", "Q", "J", "T", "9", "8", "7", "6", "5", "4", "3", "2", "1"))
df$four <- ordered(df$four, levels = c("A", "K", "Q", "J", "T", "9", "8", "7", "6", "5", "4", "3", "2", "1"))
df$five <- ordered(df$five, levels = c("A", "K", "Q", "J", "T", "9", "8", "7", "6", "5", "4", "3", "2", "1"))

df <- arrange(df, df$type, df$one, df$two, df$three, df$four, df$five)

df$rank <- rev(c(1:nrow(df)))
df$total <- df$rank * df$bid
sum(df$total)
```
# Day 7.2
```{r}
data <- read.delim("data/day7.txt", header = FALSE)

df<- as.data.frame(t(data.frame(strsplit(data$V1, split = " "))))
colnames(df) <- c("hand", "bid")
rownames(df) <- c(1:nrow(df))
df$bid <- as.numeric(df$bid)
df$type <- NA
df$one <- NA
df$two <- NA
df$three <- NA
df$four <- NA
df$five <- NA

calcmode <- function(a) {
  vector <- unique(a)
  vector[which(tabulate(match(a, vector)) == max(tabulate(match(a, vector))))]
}



for (row in 1:nrow(df)) {
  split_string <- strsplit(df$hand[row], split = "")[[1]]
  if ("J" %in% unique(split_string)) {
    if (length(calcmode(split_string)) > 1) {
      split_string <- ordered(split_string, levels = rev(c("A", "K", "Q", "T", "9", "8", "7", "6", "5", "4", "3", "2", "1", "J")))
      split_string[split_string == "J"] <- max(calcmode(split_string))
    } else if ((calcmode(split_string) == "J") & (length(calcmode(split_string[split_string != "J"])) > 1 )) {
      split_string <- ordered(split_string, levels = rev(c("A", "K", "Q", "T", "9", "8", "7", "6", "5", "4", "3", "2", "1", "J")))
      split_string[split_string == "J"] <- max(calcmode(split_string[split_string != "J"]))
    } else if ((calcmode(split_string) == "J") & length(unique(split_string))==1) {
      split_string = split_string
      } else if (calcmode(split_string) == "J") {
        
      split_string[split_string == "J"] <- calcmode(split_string[split_string != "J"])
      }else {
      split_string[split_string == "J"] <- calcmode(split_string)
    }
  }
  df$type[row] <- ifelse(length(unique(split_string))==1, 
                         "five-of-a-kind", 
                         ifelse(
                           (length(unique(split_string))==2) &
                           (sum(split_string %in% unique(split_string)[1]) %in% c(1,4)) &
                           (sum(split_string %in% unique(split_string)[2]) %in% c(1,4)), 
                            "four-of-a-kind",
                              ifelse(
                             (length(unique(split_string))==2) &
                             (sum(split_string %in% unique(split_string)[1]) %in% c(2,3)) &
                               (sum(split_string %in% unique(split_string)[2]) %in% c(2,3)),
                             "full-house", 
                             ifelse(
                               (length(unique(split_string))==3) &
                               (sum(split_string %in% unique(split_string)[1]) %in% c(1,3)) &
                               (sum(split_string %in% unique(split_string)[2]) %in% c(1,3))&
                               (sum(split_string %in% unique(split_string)[3]) %in% c(1,3)),
                               "three-of-a-kind", 
                               ifelse(
                                  (length(unique(split_string))==3) &
                               (sum(split_string %in% unique(split_string)[1]) %in% c(1,2)) &
                               (sum(split_string %in% unique(split_string)[2]) %in% c(1,2)) &
                               (sum(split_string %in% unique(split_string)[3]) %in% c(1,2)), 
                               "two-pair", 
                               ifelse(
                                 (length(unique(split_string))==4), 
                                 "one-pair", 
                                 "high-card"))))))
  
  df$one[row] <- strsplit(df$hand[row], split = "")[[1]][1]
  df$two[row] <- strsplit(df$hand[row], split = "")[[1]][2]
  df$three[row] <- strsplit(df$hand[row], split = "")[[1]][3]
  df$four[row] <- strsplit(df$hand[row], split = "")[[1]][4]
  df$five[row] <- strsplit(df$hand[row], split = "")[[1]][5]
}
df$type <- factor(df$type, ordered = TRUE, levels = c("five-of-a-kind", "four-of-a-kind", "full-house", "three-of-a-kind", "two-pair", "one-pair", "high-card"))
df$one <- ordered(df$one, levels = c("A", "K", "Q", "T", "9", "8", "7", "6", "5", "4", "3", "2", "1", "J"))
df$two <- ordered(df$two, levels = c("A", "K", "Q", "T", "9", "8", "7", "6", "5", "4", "3", "2", "1", "J"))
df$three <- ordered(df$three, levels = c("A", "K", "Q", "T", "9", "8", "7", "6", "5", "4", "3", "2", "1", "J"))
df$four <- ordered(df$four, levels = c("A", "K", "Q", "T", "9", "8", "7", "6", "5", "4", "3", "2", "1", "J"))
df$five <- ordered(df$five, levels = c("A", "K", "Q", "T", "9", "8", "7", "6", "5", "4", "3", "2", "1", "J"))

df <- arrange(df, df$type, df$one, df$two, df$three, df$four, df$five)

df$rank <- rev(c(1:nrow(df)))
df$total <- df$rank * df$bid
sum(df$total)
```
# Day 8.1
```{r}
data <- read.delim("data/day8.txt", header = FALSE)

directions <- strsplit(data$V1[1], split = "")[[1]]
map1 <- data[-1, ]
map <- data.frame(location = NA, 
                  left = NA, 
                  right = NA)
for (row in 1:length(map1)) {
  string <- map1[row]
  spl_string <-strsplit(string, split = "(\\s+)|([[:punct:]])")[[1]]
  map[row, ] <- data.frame(location = spl_string[1], 
                         left = spl_string[5], 
                         right = spl_string[7])
}
current_location = "AAA"
steps = 0
direction_num = 1
while (current_location != "ZZZ") {
  turn <- directions[direction_num]
  if (turn == "L") {
    current_location <- map[map$location == current_location, "left"]
  } else if (turn == "R") {
    current_location <- map[map$location == current_location, "right"]
  }
  direction_num <- direction_num + 1
  if (direction_num > length(directions)) {
    direction_num  = 1
  }
  steps <- steps + 1
}

print(steps)
```
# Day 8.2 - right solution, wrong answer?
```{r}
library(DescTools)
library(numbers)

data <- read.delim("data/day8.txt", header = FALSE)

directions <- strsplit(data$V1[1], split = "")[[1]]
map1 <- data[-1, ]
map <- data.frame(location = NA, 
                  left = NA, 
                  right = NA)
for (row in 1:length(map1)) {
  string <- map1[row]
  spl_string <-strsplit(string, split = "(\\s+)|([[:punct:]])")[[1]]
  map[row, ] <- data.frame(location = spl_string[1], 
                         left = spl_string[5], 
                         right = spl_string[7])
}

current_locations <- map$location[endsWith(map$location, "A")]
steps = 0
direction_num = 1
steps_for_each_path <- numeric()
for (current_location in current_locations) {
  while (endsWith(current_location, "Z") == FALSE) {
    turn <- directions[direction_num]
    if (turn == "L") {
      current_location <- map[map$location == current_location, "left"]
    } else if (turn == "R") {
      current_location <- map[map$location == current_location, "right"]
    }
    direction_num <- direction_num + 1
    if (direction_num > length(directions)) {
      direction_num  = 1
    }
    steps <- steps + 1
  }
  steps_for_each_path = c(steps_for_each_path, steps)
}

lcm_vector <- function(x) Reduce(LCM, x)
lcm_vector(steps_for_each_path)

primeFactors(steps_for_each_path[1])
primeFactors(steps_for_each_path[2])
primeFactors(steps_for_each_path[3])
primeFactors(steps_for_each_path[4])
primeFactors(steps_for_each_path[5])
primeFactors(steps_for_each_path[6])

xx <- 2 * 2 * 2 * 2 * 3 * 3 *11 * 43 * 73 * 197 * 283 * 337
# 93417675267312
xx / steps_for_each_path
```
# Day 9.1
```{r}
data <- read.delim("data/day9.txt", header = FALSE)

predictions <- numeric()
for (history in data$V1) {
  temp_df <- list() 
  count = 1
  temp_df[[count]] <- as.numeric(strsplit(history, split = " ")[[1]])
  
  while (all(temp_df[[count]] == 0) == FALSE) {
    count = count + 1
    next_row <- numeric()
    for (numbers in 1:(length(temp_df[[count - 1]])-1)) {
      next_row <- c(next_row, temp_df[[count-1]][numbers + 1] - temp_df[[count-1]][numbers])
    }
    temp_df[[count]] <- next_row
  }
  
  for (element in rev(1:length(temp_df))) {
    if (element == length(temp_df)) {
      temp_df[[element]] <- c(temp_df[[element]], 0)
    } else {
      temp_df[[element]] <- c(temp_df[[element]], temp_df[[element]][length(temp_df[[element]])] + temp_df[[element + 1]][length(temp_df[[element + 1]])])
    }
  }
  predictions <- c(predictions, temp_df[[1]][length(temp_df[[1]])])
}

sum(predictions)

```
# Day 9.2
```{r}
data <- read.delim("data/day9.txt", header = FALSE)

predictions <- numeric()
for (history in data$V1) {
  temp_df <- list() 
  count = 1
  temp_df[[count]] <- as.numeric(strsplit(history, split = " ")[[1]])
  
  while (all(temp_df[[count]] == 0) == FALSE) {
    count = count + 1
    next_row <- numeric()
    for (numbers in 1:(length(temp_df[[count - 1]])-1)) {
      next_row <- c(next_row, temp_df[[count-1]][numbers + 1] - temp_df[[count-1]][numbers])
    }
    temp_df[[count]] <- next_row
  }
  
  for (element in rev(1:length(temp_df))) {
    if (element == length(temp_df)) {
      temp_df[[element]] <- c(0, temp_df[[element]])
    } else {
      temp_df[[element]] <- c(temp_df[[element]][1] - temp_df[[element + 1]][1], temp_df[[element]])
    }
  }
  predictions <- c(predictions, temp_df[[1]][1])
}

sum(predictions)
```

